In [1]:
import tensorflow 
print(tensorflow.__version__)
print('most time we use tf1, so we must disable_v2_behavior')
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

2023-08-17 14:31:05.546250: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.13.0
most time we use tf1, so we must disable_v2_behavior
Instructions for updating:
non-resource variables are not supported in the long term


In [13]:
with tf.variable_scope('cluster_center', reuse=tf.AUTO_REUSE):
    ref = tf.get_variable(name="_emb", shape=[3, 4],initializer=tf.glorot_uniform_initializer())

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(ref))
    print(sess.run(tf.norm(ref)))

[[-0.65205836  0.8944442   0.90172577 -0.72337866]
 [-0.0388748  -0.01802546  0.54750013  0.25059366]
 [ 0.12346506  0.64824367 -0.29742676 -0.11935616]]
1.8612249


In [10]:
# a = tf.Variable([[1,1,1,1],[2,2,2,2],[3,3,3,3]],dtype=tf.float32)  # batch_size*dim
# a=tf.random.normal(shape=[3,4])
# import tensorflow as tf
with tf.variable_scope('cluster_center', reuse=tf.AUTO_REUSE):
    ref = tf.get_variable(name="_emb", shape=[3, 4],initializer=tf.glorot_uniform_initializer())
norm1= tf.norm(ref)

    
indices = tf.constant([[0],[2],[0],[1],[2]])     # (update_size,1)的二维张量，不能是(update_size,)一维张量；而且每个元素大小不能超过 batch_size-1
updates = tf.constant([[5, 5, 5, 5], [6, 6, 6, 6],
   [7, 7, 7, 7], [8, 8, 8, 8],[9,9,9,9]],dtype=tf.float32)   # update_size * hidden_dim
update = tf.scatter_nd_add(ref, indices, updates)
norm2=tf.norm(ref)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(norm1))
    print(sess.run(update))
    print(sess.run(norm2))
    
# for var in tf.trainable_variables():
#     print(var)

train_var = tf.get_collection(tf.compat.v1.GraphKeys.TRAINABLE_VARIABLES)
for var in train_var:
    print(var.name)
    if 'cluster' in var.name:
        train_var.remove(var)
print(train_var)


1.4866769
[[12.473855  12.666567  11.667095  12.338736 ]
 [ 7.4149895  7.9197845  8.073525   7.636393 ]
 [14.6843605 15.720445  15.27478   14.632128 ]]
41.902107
cluster_center/_emb:0
[]


In [10]:
li = ['xa','shsh','xb']
for ele in li:
    if 'x' in ele:
        li.remove(ele)
li

['shsh']